<template>
  <header>
    <span>Home</span>
    <span>|</span>
    <span>Jogadores</span>
    <span>|</span>
    <span>Times</span>
  </header>
  <main>Jogadores</main>
  <footer>Rodapé</footer>
</template>